// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/DanilaBorz/testovoe-itk/internal/service (interfaces: WalletService)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/wallet_service.go -package=mocks github.com/DanilaBorz/testovoe-itk/internal/service WalletService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/DanilaBorz/testovoe-itk/internal/model"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockWalletService is a mock of WalletService interface.
type MockWalletService struct {
	ctrl     *gomock.Controller
	recorder *MockWalletServiceMockRecorder
	isgomock struct{}
}

// MockWalletServiceMockRecorder is the mock recorder for MockWalletService.
type MockWalletServiceMockRecorder struct {
	mock *MockWalletService
}

// NewMockWalletService creates a new mock instance.
func NewMockWalletService(ctrl *gomock.Controller) *MockWalletService {
	mock := &MockWalletService{ctrl: ctrl}
	mock.recorder = &MockWalletServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWalletService) EXPECT() *MockWalletServiceMockRecorder {
	return m.recorder
}

// GetBalance mocks base method.
func (m *MockWalletService) GetBalance(ctx context.Context, id uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockWalletServiceMockRecorder) GetBalance(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockWalletService)(nil).GetBalance), ctx, id)
}

// ProcessOperation mocks base method.
func (m *MockWalletService) ProcessOperation(ctx context.Context, req model.OperationRequest) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessOperation", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessOperation indicates an expected call of ProcessOperation.
func (mr *MockWalletServiceMockRecorder) ProcessOperation(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessOperation", reflect.TypeOf((*MockWalletService)(nil).ProcessOperation), ctx, req)
}
