version: '3.9'

services:
  postgres-test:
    image: postgres:16-alpine
    container_name: wallet-db-test
    environment:
      POSTGRES_USER: wallet_test
      POSTGRES_PASSWORD: wallet_test_pass
      POSTGRES_DB: wallet_test_db
    ports:
      - "5433:5432"
    volumes:
      - ./migrations/001_init.sql:/docker-entrypoint-initdb.d/001_init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wallet_test -d wallet_test_db"]
      interval: 3s
      timeout: 3s
      retries: 10